### ISSUE TITLE
Have cultures carry over from Vic2 to HoI4 games

### ISSUE THREAD

**Issue by Unfunkable** [Unfunkable/HoI4-to-Stellaris-Converter#2]
Like in Hearts of Iron, it would not affect gameplay and would simply be a visual indicator. Could look into empires splitting off have the same culture as their origin empire.

**Comment by Idhrendur** [comment]
Is there any information the Vic2 to HoI4 converter can drop into the mod to make this easier?

**Comment by faris0064** [comment]
Doesn't look like it. I should be able to easily grab this from the save file.
